module.exports = Object.freeze({
    MONGO_DB: "connection-str",
    SQS_NAME: "sqs",
    RETRIES: "retries",
    DB: "db",
    DATABASE_NAME: process.env.DATABASE_NAME || 'crdc-datahub',
    FILE_INVALID_REASON: "invalid_reason",
    SUCCEEDED: "succeeded",
    ERRORS: "errors",
    WARNINGS: "warnings",
    CREATED_AT: "createdAt",
    UPDATED_AT: "updatedAt",
    STATUS: "status",
    STATUS_FAILED: "Failed",
    DATA_COMMON_NAME: "dataCommons",
    ID: "_id",
    STATUS_ERROR: "Error",
    STATUS_WARNING: "Warning",
    STATUS_PASSED: "Passed",
    STATUS_NEW: "New",
    PROPERTIES: "props",
    LAST_MODIFIED: "LastModified",
    VERSION: "version",
    MODEL_SOURCE: "source_files",
    NAME_PROP: "name",
    DESC_PROP: "description",
    ID_PROPERTY: "id_property",
    MODEL: "model",
    VALUE_PROP: "value",
    VALUE_EXCLUSIVE: "exclusive",
    ALLOWED_VALUES: "permissible_values",
    RELATION_LABEL: "label",
    NODE_PROPERTIES: "properties",
    TYPE: "type",
    MODELS_DEFINITION_FILE: "content.json",
    MODEL_FILE_DIR: "models-loc",
    TIER: "TIER",
    TIER_CONFIG: "tier",
    FILE_SIZE: "file_size",
    MIN: "minimum",
    MAX: "maximum",
    VALIDATION_RESULT: "result",
    VALIDATED_AT: "validatedAt",
    MODEL_VERSION: "modelVersion",
    KEY: "key",
    LIST_DELIMITER_PROP: "list-delimiter",
    ROOT_PATH: "rootPath",
    ALLOWED_VALUES: "allowedValues",
  
    FAILED: "Failed",
    ADDITION_ERRORS: "additionalErrors",
    STUDY_ABBREVIATION: "studyAbbreviation",
    LIST_DELIMITER_PROP: "list-delimiter",
    CONTROL_ACCESS: "controlledAccess",
    CDE_COLLECTION: "CDE",
    CDE_CODE: "CDECode",
    CDE_VERSION: "CDEVersion",
    CDE_API_URL: "cde-data-element-api",
    CDE_TERM: "Term",
    CDE_PERMISSIVE_VALUES: "PermissibleValues",
    DEF_VERSION: "versions",
    SYNONYM_COLLECTION: "synonyms",
  
    TERM_CODE: "Code",
    TERM_VERSION: "Version",

    MAX_ALLOWED_LENGTH: 255,
  });
  